version: '3.3'

services:
  connector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connector

  mosquitto:
    image: mbixtech/arm32v7-mosquitto:latest
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto:/mosquitto

  db:
    image: hypriot/rpi-mysql
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    volumes:
      - ./mysql/config:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql

