version: '3.3'
services:
  connector:
    build: .
    container_name: connector

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
    - ./mosquitto:/mosquitto
#    - script:
#        - pytest ...

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/config:/docker-entrypoint-initdb.d

  graphana:
    image: grafana/grafana:5.2.4
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - GF_PLUGIN_DIR=/pluginfolder
    volumes:
      - .grafana:/var/lib/grafana
      - .grafana/pluginfolder:/var/lib/pluginfolder