version: '3.3'
services:
  connector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connector

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto:/mosquitto
  
  db:
    image: hypriot/rpi-mysql
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/config:/etc/mysql/conf.d/
      - ./mysql/db:/var/lib/mysql
