version: '3.3'
services:
  connector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connector

  mosquitto:
    image: mbixtech/arm32v7-mosquitto:latest
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto:/mosquitto

  db:
    image: hypriot/rpi-mysql
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/config:/etc/mysql/conf.d/
      - ./mysql/db:/var/lib/mysql

  grafana:
    image: grafana/grafana:5.2.4
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - GF_PLUGIN_DIR=/pluginfolder
    volumes:
      - ./grafana:/var/lib/grafana

